# Generated by Django 4.1.7 on 2023-05-22 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourist_attractions', '0003_alter_attraction_homestate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='stateAbbreviation',
        ),
    ]
